baseURL: "https://www.badrchoubai.dev"
title: "Badr Choubai"
pagination:
  pagerSize: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true

disableKinds:
  - "taxonomy"
  - "term"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Badr Choubai"
  description: "Badr Choubai | Boulder, CO."
  keywords: [Blog]
  author: Badr Choubai
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  # https://github.com/adityatelange/hugo-PaperMod/issues/940
  # to support ShowPostNavLinks, but they will show up in home page...
  mainSections:
    - posts

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/favicon.ico"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  # label:
  #   text: "" # use a space to pretend not to show text
  #   icon: ""
  #   iconHeight: 20

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: >
      Hello :wave:
    buttons:
      - name: About
        url: /about
      - name: Posts
        url: /posts

  # home-info mode
  homeInfoParams:
    Title: "Hello :wave:"
    Content: >
      I'm a Moroccan-American software engineer from Aurora, Colorado. My name—Badr (بدر)—means "The Full Moon" in Arabic.

      In the last year, I started learning Go, developing small applications with it and continuing to grow my knowledge
      of Docker and Kubernetes, making the effort to study to pass the Certified Kubernetes Administrator exam.

      I'm  actively looking for a new role where I can continue developing my skills, particularly in Developer Operations
      or Platform Engineering. Ideally, I'm looking for a company with a mature remote working culture that strikes the right
      balance between flexibility and productivity. As a young professional, I'm passionate about continuous learning and
      growth, and I'm excited about the opportunity to apply my skills in a new, challenging environment.

  socialIcons:
    - name: github
      url: "https://github.com/BadrChoubai"
    - name: linkedin
      url: "https://linkedin.com/in/BadrChoubai"
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    contentDir: content
    disabled: false
    languageName: English
    weight: 1

menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: About
      url: /about
      weight: 20
    - name: Posts
      url: /posts/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

